MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    MULTILEVEL_RPN: False
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 9
    NUM_SUPERCLASSES: 5
    SUPERCLASS_MAP: (0, 0, 1, 1, 1, 2, 2, 2, 3, 4)  # ped_rider(0), car_truck_bus(1), ts(2), tl(3), ignored(4)
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    USE_DIRICHLET_LOSS: False
    DIRICHLET_LOSS_LAMBDA: 0.0
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  IGNORED_CLASS_INDEX: 9  # from index zero 
DATASETS:
  # TRAIN: ("coco_2017_train",)
  # TEST: ("coco_2017_val",)
  TRAIN: ("udb_skt", "udb_gopro", "udb_gopro_kor", "udb_harman", "udb_hondari", "udb_movon_ger_od_tstld", "udb_movon_kor", "udb_movon_usa", "udb_youtube", "udb_200225")
  # TEST: ("udb_test_200225", "udb_test_191204_mobis", "udb_test_svnetr1_zf")  
  TEST: ("udb_test_200225",)  
SOLVER:
  IMS_PER_BATCH: 32  #16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
