_BASE_: "../Base-RCNN-BiFPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE_AT: 0
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  BASE_LR: 0.004
