_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE_AT: 0
  ROI_HEADS:
    NUM_SUPERCLASSES: 1
SOLVER:
  BASE_LR: 0.004  
  STEPS: (220000, 260000)
  MAX_ITER: 280000
  IMS_PER_BATCH: 27
INPUT:
  MIN_SIZE_TRAIN: (360,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 360
  MAX_SIZE_TEST: 640
