# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: True # Update full network in SCAN
num_heads: 10 # Only use one head

# Model
backbone: resnet50

# Dataset
train_db_name: svkpi_v2
val_db_name: svkpi_v2
num_classes: 27
num_neighbors: 30

# Transformations
augmentation_strategy: simclr 
augmentation_kwargs:
   random_resized_crop:
      size: 608
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

transformation_kwargs:
   crop_size: 608
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer: sgd
optimizer_kwargs:
   lr: 5.0
   weight_decay: 0.0000
   nesterov: False
   momentum: 0.9
epochs: 1000
batch_size: 64
num_workers: 4

# Scheduler
scheduler: constant
