# Setup
setup: moco # MoCo is used here

# Model
backbone: resnet50
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: svkpi_v2
val_db_name: svkpi_v2
num_classes: 30
temperature: 0.07

# Batch size and workers
batch_size: 32 
num_workers: 0

# Transformations
transformation_kwargs:
   crop_size: 608
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
